# ------------------------------------------------------------
# Postman collection generation helpers
# ------------------------------------------------------------
# These functions turn a TestPlan into a Postman v2.1 collection
# that you can import directly into the Postman Desktop app.
#
# Design notes:
#   - We generate a minimal but valid v2.1 collection
#   - Each TestCase becomes one Postman "item"
#   - URL and body are placeholders; you edit them in Postman
#   - We attach a basic JavaScript test script to each item
# ------------------------------------------------------------

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any, Dict
from uuid import uuid4

from vigilancepilot.models import TestPlan, TestCase


def _build_postman_item_from_test_case(
    test_case: TestCase,
    base_url_variable: str = "{{baseUrl}}",
) -> Dict[str, Any]:
    """
    Convert a single TestCase into a Postman "item" object.

    Parameters:
        test_case:         One VigilancePilot TestCase instance.
        base_url_variable: The Postman variable used for the base URL
                           (kept as {{baseUrl}} so you can override it in Postman).

    Returns:
        A Python dict matching the Postman v2.1 "item" schema.
    """

    # NOTE: We do NOT try to parse the path/method from the requirement yet.
    #       Everything defaults to POST {{baseUrl}}/TODO-path
    #       so it's always valid but clearly marked for you to edit.
    item_name = f"{test_case.id} - {test_case.category} - {test_case.description}"

    # Basic test script that checks the response status code.
    # You can expand this in Postman to check body shape, headers, etc.
    test_script_lines = [
        "// Basic status code check generated by VigilancePilot",
        "pm.test('Status code is 200', function () {",
        "    pm.response.to.have.status(200);",
        "});",
    ]

    item: Dict[str, Any] = {
        "name": item_name,
        "request": {
            # HTTP method is a placeholder; change it per endpoint.
            "method": "POST",
            "header": [],
            "url": {
                # Raw URL string Postman shows in the UI.
                "raw": f"{base_url_variable}/TODO-path",
                # Host split into segments; here it's just the variable.
                "host": [base_url_variable.strip("{}")],
                # Path segments; TODO for the user to fill in.
                "path": ["TODO-path"],
            },
            "body": {
                "mode": "raw",
                # Placeholder JSON body; you customize it in Postman.
                "raw": "{\n  // TODO: fill in request body based on your API\n}",
                "options": {
                    "raw": {
                        "language": "json",
                    }
                },
            },
        },
        "event": [
            {
                # Attach the basic test script
                "listen": "test",
                "script": {
                    "type": "text/javascript",
                    "exec": test_script_lines,
                },
            }
        ],
    }

    return item


def build_postman_collection_object(
    test_plan: TestPlan,
    base_url_default: str = "https://api.example.com",
) -> Dict[str, Any]:
    """
    Build the full Postman collection object (v2.1) from a TestPlan.

    Parameters:
        test_plan:       VigilancePilot TestPlan produced from a requirement.
        base_url_default:Default value for the {{baseUrl}} Postman variable.

    Returns:
        A Python dict representing the full collection JSON.
    """

    items: list[Dict[str, Any]] = []

    # One Postman "item" per TestCase in the plan
    for case in test_plan.generated_cases:
        items.append(_build_postman_item_from_test_case(case))

    collection: Dict[str, Any] = {
        "info": {
            "name": f"VigilancePilot – {test_plan.requirement}",
            "_postman_id": str(uuid4()),
            # Official Postman v2.1 collection schema URL
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
            "description": (
                "Collection auto-generated by VigilancePilot from a natural-language "
                "requirement. Edit paths, methods, and bodies as needed."
            ),
        },
        "item": items,
        "variable": [
            {
                "key": "baseUrl",
                "value": base_url_default,
                "type": "string",
                "description": "Base URL placeholder. Update this to match your API host.",
            }
        ],
    }

    return collection


def export_postman_collection(
    test_plan: TestPlan,
    output_dir: Path,
) -> Path:
    """
    Convert a TestPlan into a Postman collection JSON file and write it to disk.

    Parameters:
        test_plan:  VigilancePilot TestPlan instance to export.
        output_dir: Folder where the .postman_collection.json file will be written.

    Returns:
        Path to the generated JSON file.
    """
    import json

    # Ensure the output directory exists (create nested folders if needed).
    output_dir.mkdir(parents=True, exist_ok=True)

    # Build a filename that is stable and human-readable.
    # Example: vigilancepilot_20251121_121530.postman_collection.json
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    filename = f"vigilancepilot_{timestamp}.postman_collection.json"
    output_path = output_dir / filename

    # Build the in-memory collection object
    collection_obj = build_postman_collection_object(test_plan)

    # Serialize to JSON with indentation so it is easy to inspect in Git.
    with output_path.open("w", encoding="utf-8") as f:
        json.dump(collection_obj, f, indent=2)

    return output_path
